### ISSUE TITLE
why not use setInterval?

### ISSUE THREAD

**Issue by jbenet** [juliangruber/periodic#1]
why not use setInterval? (instead of setTimeouts)

**Comment by juliangruber** [comment]
Say you have this piece of code:

``` js
setInterval(function(){
  // do something
}, 1000);
```

Since JavaScript is based on one event loop, the promise of `setInterval` is to run the passed function "after x ms or later", so it's possible and likely that the delay is slightly bigger than 1 second. Over time this interval will be thrown off a lot.

periodic makes up for this by adjusting the current wait time based on the so far elapsed time.
